import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { handlePublicConsultationAssistant } from "@/server/consultations/consultation-assistant-service";
import * as availability from "@/server/consultations/consultation-availability-service";
vi.mock("@/server/rate-limit/memory-rate-limit",()=>({enforceRateLimit:vi.fn(),rateLimiters:{ai:{},booking:{}}}));
const draft={fullName:"Hala Samir",phone:"+201000009911",summary:"A supplier agreement requires a scheduled document review.",serviceCategory:"corporate-business-services",preferredMode:"ONLINE"};
const ask=async()=>await handlePublicConsultationAssistant({body:{locale:"en",message:"Please help arrange the consultation for this matter",draft},request:new Request("http://example.test"),requestId:"batch5-provider"}) as any;
beforeEach(()=>{vi.stubEnv("AI_PROVIDER","local");vi.stubEnv("AI_BASE_URL","http://provider.test/v1");vi.stubEnv("AI_API_KEY","");vi.stubEnv("AI_TIMEOUT_MS","1000");vi.spyOn(availability,"listPublicConsultationSlots").mockResolvedValue([]);});
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe("batch5 provider adapter/gateway failure boundaries (fetch stub, no network)",()=>{
 it.each(["http503","http429","malformed-json","invalid-shape"])("preserves intake after %s",async kind=>{const output=kind==="malformed-json"?"not JSON":JSON.stringify({invented:"no schema"});const fetcher=vi.fn(async()=>kind.startsWith("http")?new Response("Unavailable",{status:Number(kind.slice(4))}):Response.json({choices:[{message:{content:output}}]}));vi.stubGlobal("fetch",fetcher);const r=await ask();expect(fetcher).toHaveBeenCalledTimes(1);expect(r.draft.phone).toBe(draft.phone);expect(r.draft.fullName).toBe(draft.fullName);expect(r.reference).toBeUndefined();expect(r.readyToConfirm).toBe(false);});
 it("aborts a slow provider at the configured timeout and preserves the draft",async()=>{vi.useFakeTimers();let aborted=false;vi.stubGlobal("fetch",vi.fn((_url,init)=>new Promise((_resolve,reject)=>{init.signal.addEventListener("abort",()=>{aborted=true;reject(new DOMException("Aborted","AbortError"));});})));const pending=ask();await vi.advanceTimersByTimeAsync(1001);const r=await pending;expect(aborted).toBe(true);expect(r.draft.phone).toBe(draft.phone);expect(r.reference).toBeUndefined();});
 it("does not trust a high-confidence impossible calendar preference",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>Response.json({choices:[{message:{content:JSON.stringify({intent:"booking",fields:{availabilityPreference:{date:"2026-13-01"}},fieldConfidence:{availabilityPreference:0.99},confidence:0.99,needsClarification:false,clarifyingQuestion:null,legalAdviceRequested:false,reviewNote:"Review required"})}}]})));const r=await ask();expect(r.draft.availabilityPreference.date).toBe("");expect(r.draft.phone).toBe(draft.phone);});
});
