export const directBookingCopy = {
  ar: {
    openForm: "استكمال بيانات الحجز", openDetails: "عرض تفاصيل الطلب", closeForm: "إغلاق والعودة للمحادثة", formHelp: "اختر الموعد وأدخل اسمك ورقم هاتفك، ثم اضغط زر التأكيد لإرسال الطلب للمكتب. إغلاق النافذة وحده لا يرسل الطلب؛ تبقى مدخلاتك عند فتحها مجددًا في هذه الصفحة.",
    title: "اختيار موعد للتواصل مع محامٍ", intro: "اختر وقتًا مناسبًا ليتواصل معك محامٍ من المكتب. الأتعاب منفصلة عن تثبيت الموعد.",
    phone: "مكالمة هاتفية", whatsapp: "التواصل عبر واتساب", channel: "طريقة التواصل", name: "الاسم", number: "رقم الهاتف", date: "اختيار يوم آخر", nearest: "أقرب المواعيد", choose: "اختر الموعد", confirm: "تأكيد الموعد", review: "راجع الموعد والاسم والرقم قبل التأكيد", consent: "راجعت البيانات وأوافق على تثبيت الموعد والتواصل معي.",
    empty: "لا توجد مواعيد متاحة للاختيار حاليًا. يمكنك تجربة يوم آخر أو ترك طلب تواصل دون موعد مؤكد.", callback: "تسجيل طلب تواصل دون موعد", callbackDone: "تم تسجيل طلب التواصل؛ لم يُحدد موعد مؤكد بعد.", confirmed: "تم تأكيد الموعد. سيتواصل معك المحامي بالطريقة التي اخترتها؛ لا تحتاج للبقاء في صفحة المحادثة.", cancelled: "تم إلغاء الموعد.", reference: "رقم الحجز", cairo: "بتوقيت القاهرة", minutes: "دقيقة", lawyer: "المحامي", change: "تغيير الموعد", cancel: "إلغاء الموعد", cancelConfirm: "أؤكد إلغاء هذا الموعد", calendar: "إضافة إلى التقويم", keep: "الاحتفاظ بالموعد الحالي", conflict: "الموعد لم يعد متاحًا أو لديك حجز نشط. بياناتك محفوظة؛ اختر بديلًا أو تواصل مع المكتب.", failed: "تعذر إتمام الإجراء. بياناتك محفوظة؛ أعد المحاولة.", waiting: "جارٍ التحقق…", retry: "إعادة المحاولة", optionalAccount: "إنشاء حساب للمتابعة اختياري؛ حجزك لا ينتظر تفعيل البريد.", defaultSummary: "التواصل مع المكتب بشأن خدماته القانونية.", appointmentTitle: "موعد تواصل مع KMT Legal", expired: "بعد انتهاء هذه الجلسة، يمكنك متابعة الحجز من حسابك إن ربطته، أو التواصل مع المكتب للتعديل والإلغاء.",
    queued: "طلب التواصل في انتظار استلام فريق المكتب. يمكنك اختيار موعد ليتواصل معك محامٍ، ولا تحتاج للبقاء منتظرًا هنا.", claimed: "استلم فريق المكتب المحادثة. يمكنك إرسال رسالة أو استخدام خيارات الحجز؛ الرد الآلي متوقف أثناء متابعة الموظف.", fallback: "فهمت أنك تحتاج مساعدة من المكتب. لا تتوفر لديّ تفاصيل معتمدة إضافية لهذه النقطة؛ يمكنك اختيار موعد للتحدث مع محامٍ.",
    adminTitle: "الحجز المباشر مع المحامين", publish: "نشر الجدول والسماح بالتأكيد المباشر", adminNote: "النشر يعتمد هذه المواعيد مسبقًا. يُحجز موعد واحد في الفترة نفسها ويُسند لمحامٍ متفرغ من القائمة اليومية. لا يغيّر تعديل الجدول الحجوزات السابقة.", roster: "المحامون المشاركون في هذا اليوم", closures: "الإجازات والفترات المغلقة", addClosure: "إضافة فترة مغلقة", remove: "حذف الفترة", allLawyers: "كل المحامين", closureDate: "التاريخ", closureStart: "من", closureEnd: "إلى", closureLawyer: "المحامي أو المكتب", source: "طريقة اعتماد الموعد", sources: { STAFF_APPROVAL: "مراجعة الإدارة", PUBLISHED_SLOT: "جدول معتمد مسبقًا", CALLBACK_REQUEST: "طلب تواصل دون موعد" }
  },
  en: {
    openForm: "Continue booking details", openDetails: "View request details", closeForm: "Close and return to chat", formHelp: "Choose a time and enter your name and phone, then use the confirmation button to send your request to the office. Closing this window does not send it; your entries remain when you reopen it on this page.",
    title: "Choose a time to speak with a lawyer", intro: "Choose a suitable time for an office lawyer to contact you. Fees are separate from appointment confirmation.",
    phone: "Phone call", whatsapp: "Contact via WhatsApp", channel: "Contact method", name: "Name", number: "Phone number", date: "Choose another day", nearest: "Nearest available times", choose: "Choose a time", confirm: "Confirm appointment", review: "Review your appointment, name and phone before confirming", consent: "I have reviewed the details and agree to this appointment and being contacted.",
    empty: "No selectable times are available right now. Try another day or leave a contact request without a confirmed appointment.", callback: "Leave a contact request", callbackDone: "Your contact request was recorded. No appointment is confirmed yet.", confirmed: "Your appointment is confirmed. The lawyer will contact you using your chosen method; you do not need to stay in this conversation.", cancelled: "Your appointment was cancelled.", reference: "Booking reference", cairo: "Cairo time", minutes: "minutes", lawyer: "Lawyer", change: "Change appointment", cancel: "Cancel appointment", cancelConfirm: "Confirm cancellation", calendar: "Add to calendar", keep: "Keep current appointment", conflict: "This time is no longer available or you have an active booking. Your details are retained; choose an alternative or contact the office.", failed: "We could not complete this action. Your details are retained; try again.", waiting: "Checking availability…", retry: "Try again", optionalAccount: "Creating an account for follow-up is optional; your booking does not wait for email verification.", defaultSummary: "Contact the office about its legal services.", appointmentTitle: "KMT Legal contact appointment", expired: "After this session expires, follow the booking from your linked account, or contact the office to change or cancel it.",
    queued: "Your contact request is waiting for the office team to pick it up. You can choose a time for a lawyer to contact you without waiting here.", claimed: "The office team has taken over this conversation. You can send a message or use the booking options; automatic replies are paused while staff handles it.", fallback: "I understand you need help from the office. I do not have further approved details for this point; you can choose a time to speak with a lawyer.",
    adminTitle: "Direct lawyer booking", publish: "Publish schedule and allow direct confirmation", adminNote: "Publishing preapproves these times. One appointment is booked per time interval and assigned to an available daily roster lawyer. Schedule edits do not change existing bookings.", roster: "Participating lawyers for this day", closures: "Holidays and closed periods", addClosure: "Add closed period", remove: "Remove period", allLawyers: "All lawyers", closureDate: "Date", closureStart: "From", closureEnd: "To", closureLawyer: "Lawyer or office", source: "Confirmation policy", sources: { STAFF_APPROVAL: "Office review", PUBLISHED_SLOT: "Preapproved schedule", CALLBACK_REQUEST: "Contact request without appointment" }
  }
} as const;
